service: aws-lambda-padlock-api
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  profile: deploy-padlock # user created in aws
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-3 #Paris

functions:
  getUser:
    handler: users.getUser
    events:
      - http:
          path: /api/users/{user_id}
          request:
            parameters:
              paths:
                user_id: true
          method: get
  newUser:
    handler: users.newUser
    events:
      - http:
          path: /api/users/new
          method: post
  deleteUser:
    handler: users.deleteUser
    events:
      - http:
          path: /api/users/delete/{user_id}
          request:
            parameters:
              paths:
                user_id: true
          method: delete
  editUserEmail:
    handler: users.editUserEmail
    events:
      - http:
          path: /api/users/Email/edit/{editUserE_id}
          request:
            parameters:
              paths:
                editUserE_id: true
          method: put
  editUserPass:
    handler: users.editUserPass
    events:
      - http:
          path: /api/users/Pass/edit/{editUserP_id}
          request:
            parameters:
              paths:
                editUserP_id: true
          method: put
