service: aws-lambda-padlock-api
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  profile: deploy-padlock # user created in aws
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-3 #Paris

functions:
  users:
    handler: routes/api/users.handler
    events:
      - http:
          path: /api/users/{user_id}
          request:
            parameters:
              paths:
                user_id: true
          method: get
      - http:
          path: /api/users/{user_id}
          request:
            parameters:
              paths:
                user_id: true
          method: post
      - http:
          path: /api/users/{user_id}
          request:
            parameters:
              paths:
                user_id: true
          method: delete
      - http:
          path: /api/users/{user_id}/password
          request:
            parameters:
              paths:
                user_id: true
          method: put
      - http:
          path: /api/users/{user_id}/email
          request:
            parameters:
              paths:
                user_id: true
          method: put
  # services:
  #   handler: routes/api/services.handler
  #   events:
  #     - http:
  #         path: /api/services/
  #         method: get
  #     - http:
  #         path: /api/services/{user_id}/{service_id}/my_data
  #         request:
  #           parameters:
  #             paths:
  #               user_id: true
  #               service_id: true
  #         method: post
  #     - http:
  #         path: /api/services/{service_id}
  #         request:
  #           parameters:
  #             paths:
  #               service_id: true
  #         method: delete
  #     - http:
  #         path: /api/users/{service_id}/name
  #         request:
  #           parameters:
  #             paths:
  #               service_id: true
  #         method: put
  #     - http:
  #         path: /api/users/{service_id}/pass
  #         request:
  #           parameters:
  #             paths:
  #               service_id: true
  #         method: put
  #     - http:
  #         path: /api/users/{service_id}/bio
  #         request:
  #           parameters:
  #             paths:
  #               service_id: true
  #         method: put
